// src/atoms/Button/Button.tsx
import React, { ButtonHTMLAttributes } from 'react';
import Icon from "../Icon/Icon.tsx";

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost' | 'dark' | 'pill';
  icon?: string | null;
  iconOnly?: boolean;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  icon = null,
  iconOnly = false,
  disabled = false,
  children,
  onClick,
  ...props
}) => {
  // Variant classes
  const variantClass = {
    'btn-primary': variant === 'primary',
    'btn-secondary': variant === 'secondary',
    'btn-ghost': variant === 'ghost',
    'btn-dark': variant === 'dark',
    'btn-pill': variant === 'pill',
  };

  // Convert class objects to strings
  const variantClassString = Object.keys(variantClass)
    .filter(key => variantClass[key as keyof typeof variantClass])
    .join(' ');

  const disabledClass = disabled ? 'opacity-50 cursor-not-allowed' : '';

  return (
    <button
      className={`btn ${variantClassString} ${iconOnly ? 'btn-icon-only' : ''} ${disabledClass}`}
      disabled={disabled}
      onClick={onClick}
      {...props}
    >
      { icon && <Icon name={icon} size={18} /> }
      { children }
    </button>
  );
};

export default Button;

// src/components/Button/Button.vue
<template>
  <button
    :class="[
      'btn',
      variantClass,
      sizeClass,
      { 'opacity-50 cursor-not-allowed': disabled }
    ]"
    :disabled="disabled"
    @click="onClick"
  >
    <slot></slot>
  </button>
</template>

<script>
export default {
  name: 'Button',
  props: {
    variant: {
      type: String,
      default: 'primary',
      validator: (value) => ['primary', 'secondary', 'white'].includes(value)
    },
    size: {
      type: String,
      default: 'md',
      validator: (value) => ['sm', 'md', 'lg'].includes(value)
    },
    disabled: {
      type: Boolean,
      default: false
    }
  },
  computed: {
    variantClass() {
      // Using static classes that Tailwind can detect
      return {
        'btn-primary': this.variant === 'primary',
        'btn-secondary': this.variant === 'secondary',
        'btn-white': this.variant === 'white'
      }
    },
    sizeClass() {
      // Size classes
      return {
        'btn-sm': this.size === 'sm',
        'btn-md': this.size === 'md',
        'btn-lg': this.size === 'lg'
      }
    }
  },
  methods: {
    onClick(event) {
      this.$emit('click', event)
    }
  }
}
</script>
